
select * from CLIENTE
select * from ALQUILER
select * from DISTRITO
select * from AUTOMOVIL
select * from DETALLEALQUILER


SELECT DA.NUM_ALQ, CL.IDE_CLI, CL.APE_CLI + ' ' + CL.NOM_CLI AS [CLIENTE], DA.MAT_AUT, AU.COL_AUT, AU.MOD_AUT, AL.FEC_ALQ
FROM DetalleAlquiler DA INNER JOIN Automovil AU ON DA.MAT_AUT = AU.MAT_AUT 
	INNER JOIN Cliente CL ON CL.IDE_CLI = DA.IDE_CLI
	INNER JOIN Alquiler AL ON AL.NUM_ALQ = DA.NUM_ALQ